# Generated by Django 3.1.1 on 2020-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Print', '0002_auto_20200826_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='is_print_3d',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='printfile',
            name='is_print_cnc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='printfile',
            name='is_print_file_gcode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='printfile',
            name='is_tool_installed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='print_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
