# Generated by Django 3.1 on 2020-08-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Print', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintFiles',
            new_name='PrintFile',
        ),
    ]
