# Generated by Django 3.1.1 on 2020-10-13 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Print', '0003_auto_20200917_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='is_print_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='is_print_cnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='is_print_file_gcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='is_tool_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='print_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
