# Generated by Django 3.1.1 on 2020-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0003_auto_20200917_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTrackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_jobs', models.IntegerField(default=0)),
                ('total_print_jobs', models.IntegerField(default=0)),
                ('successful_prints', models.IntegerField(default=0)),
                ('error_prints', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='error_prints',
        ),
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='number_of_jobs',
        ),
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='successful_prints',
        ),
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='total_print_jobs',
        ),
    ]
