# Generated by Django 3.1.1 on 2020-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0004_auto_20200917_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashpaneldata',
            name='total_print_time',
            field=models.IntegerField(),
        ),
    ]
