# Generated by Django 3.1.1 on 2020-10-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0005_auto_20201013_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='temp_bed',
        ),
        migrations.RemoveField(
            model_name='dashpaneldata',
            name='temp_nozzle',
        ),
    ]
