# Generated by Django 3.1 on 2020-08-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashPanelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_bed', models.FloatField()),
                ('temp_nozzle', models.FloatField()),
                ('time_of_print_start', models.DateTimeField()),
                ('time_of_print_finish', models.DateTimeField()),
                ('total_print_time', models.TimeField()),
                ('type_of_print', models.CharField(max_length=10)),
                ('number_of_jobs', models.IntegerField()),
                ('machine_state', models.CharField(max_length=15)),
                ('file_name', models.CharField(max_length=255)),
                ('tool_installed', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TempData',
        ),
    ]
