# Generated by Django 3.1.1 on 2020-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0008_auto_20201013_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashpaneldata',
            name='type_of_print',
            field=models.CharField(max_length=20),
        ),
    ]
