# Generated by Django 3.1.1 on 2020-10-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0009_auto_20201013_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printtrackdata',
            old_name='total_print_jobs',
            new_name='Undergoing_jobs',
        ),
    ]
